version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(actions)"
    assignees:
      - 5h0utat0t2uka

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
    labels:
      - dependencies
      - pre-commit
    commit-message:
      prefix: "chore(pre-commit)"
    assignees:
      - 5h0utat0t2uka
