repos:
  - repo: https://github.com/betterleaks/betterleaks
    rev: 6475f3fe49bf893d7713cd501131176a051f8d10  # v1.6.0
    hooks:
      - id: betterleaks-system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-merge-conflict

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: e3eebf65325ccc992422292cb7a4baee967cf815  # v1.26.1
    hooks:
      - id: zizmor
