name: nix-check

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'nix/flake.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    name: Nix Flake Check
    runs-on: macos-26
    permissions:
      contents: read # actions/checkout

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: DeterminateSystems/determinate-nix-action@bafaa638b9d5ec0e7e3ac1a7fc80453ef1fd265f # v3.20.0
        with:
          kvm: false

      - name: Use Cachix
        uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: 5h0uta
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix --version

      - name: flake check
        shell: bash
        run: |
          set -euo pipefail
          cd nix
          nix flake check

      - name: eval each darwin host
        shell: bash
        run: |
          set -euo pipefail
          cd nix
          for h in hosts/darwin/*; do
            [[ -d "$h" ]] || continue
            hn="$(basename "$h")"
            echo "==> evaluating $hn"
            nix eval ".#darwinConfigurations.${hn}.config.system.build.toplevel" >/dev/null
          done

      # - name: build each darwin host
      #   shell: bash
      #   run: |
      #     set -euo pipefail
      #     cd nix
      #     for h in hosts/darwin/*; do
      #       [[ -d "$h" ]] || continue
      #       hn="$(basename "$h")"
      #       echo "==> building $hn"
      #       nix build -L ".#darwinConfigurations.${hn}.system" --no-link
      #     done
